name: Python Application Test with Github Actions by Peter
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:                    # Global permissions configuration starts here
  contents: read                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.x, 3.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os}}
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v1
        with: 
          python-version: 3.10.15
          
      - name: install packages and dependencies
        run: |
          make install
      - name: lint with pylint
        run: |
          make lint
      - name: test with pytest
        run: |
          make test
      - name: format with black 
        run: |
          make format
      - name: test all 
        run: |
          make all
